### ISSUE TITLE
TypeError in 0.3.0

### ISSUE THREAD

**Issue by DDaxler** [goerz/better-apidoc#15]
Now getting:

Exception occurred:
documenter = get_documenter(app=APP, obj=member, parent=mod)
TypeError: get_documenter() got an unexpected keyword argument 'app'

**Comment by goerz** [comment]
Is this with Sphinx 1.7?

**Comment by TTYangAS** [comment]
No it's Sphinx v1.8.5

**Comment by goerz** [comment]
You're right. This is why I have a hate-love relationship with Sphinx. They changed the API for the `get_documenter` function 4 times between v1.6 and v2.0!

**Comment by goerz** [comment]
Just pushed version 0.3.1, which hopefully works for any version of Sphinx
