### ISSUE TITLE
Update to Sphinx v1.7

### ISSUE THREAD

**Issue by pschillinger** [goerz/better-apidoc#5]
Hey,

thank you for the useful template integration to apidoc! Unfortunately, it appears to be out of sync with sphinx since their recent update to v1.7:
[https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/apidoc.py](https://github.com/sphinx-doc/sphinx/blob/f8bb40ab308b5daacfe45979a4e42fa82f8ef8ed/sphinx/ext/apidoc.py)

In particular, the following line gives an import error now:

https://github.com/goerz/better-apidoc/blob/b52b365ea492376ca4011bf96741a81e6bced0e8/better_apidoc.py#L35

since [it changed](https://github.com/sphinx-doc/sphinx/blob/10991cdf671cb1dc4a7cdd4eb6efdea08c968ce3/sphinx/ext/apidoc.py#L31) to `from sphinx.cmd.quickstart import EXTENSIONS`.

Thanks a lot for an update!

**Comment by EricG-Personal** [comment]
I believe there are plans to actually integrate better-apidoc into Sphinx itself, but perhaps there is a quick fix for this issue to keep better-apidoc going until that work can happen.

**Comment by EricG-Personal** [comment]
Any idea when you will release version 0.1.3 with this fix?

**Comment by goerz** [comment]
done
